# Use official Python image as base
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy local files into container
COPY hello.py .

# Default command to run when container starts
CMD ["python", "hello.py"]


#   Output   
#   Hello, World from my feature branch!
